# Hyperparameters
NUM_EPOCHS: 10
LEARNING_RATE: 1e-4
BATCH_SIZE: 32
IMAGE_SIZE: 64
CHANNELS_IMG: 3
Z_DIM: 100
FEATURES_CRITIC: 64
FEATURES_GEN: 64
CRITIC_ITERATIONS: 5
LAMBDA_GP: 10
DATA_NAME: celeba_gan
DEVICE: cuda